### ISSUE TITLE
Meeting notes

### ISSUE THREAD

**Issue by jaivardhankapoor** [mackelab/labproject#4]
- [x] manual seeding function for torch, numpy, determinism
- [x] homogenize everything to torch
- [x] separate run.py (run_{name}.py) for everyone, including configs/conf_{name}.yaml for exp_name, dataset
- [x] Include plots/ in .gitignore
- [x] data.py functions, decorator that changes numpy to torch if needed (@cast_to_torch)
- [x] metrics.py, shape checking to (N,D)
- [x] Add github issue (general with common checklist) and checklist for different issues (writing, metri coding etc.)

Comment which parts you work with

**Comment by jaivardhankapoor** [comment]
@jaivardhankapoor
- [x] 7. Add github issue (general with common checklist) and checklist for different issues (writing, metri coding etc.)
- [x] 4. Include plots/ in .gitignore

**Comment by manuelgloeckler** [comment]
@manuelgloeckler 
- [x] 1. Seeding
- [x] 5. data decorator
- [x] 6. shape checking
